version: '3.8'

services:
    # Laravel App Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: owasp_laravel_app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        networks:
            - laravel_network
        command: php artisan serve --host=0.0.0.0 --port=8000

    # MySQL Database Service
    mysql:
        image: mysql:8.0
        container_name: owasp_db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: owasp_db
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_network

networks:
    laravel_network:

volumes:
    db_data:
