version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        volumes:
            - .:/var/www/html
        environment:
            - DB_HOST=mysql
        depends_on:
            - mysql

    webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: laravel_mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - mysql_data:/var/lib/mysql

    redis:
        image: redis:alpine
        container_name: laravel_redis
        ports:
            - "6379:6379"

volumes:
    mysql_data:
